# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - mstabryla-portfolio

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Vue.js - Install Dependencies
        run: |
          cd PortfolioClient
          npm install

      - name: Vue.js - Build & Deploy
        run: | 
          cd PortfolioClient
          npm run build
          ls dist
          Copy-Item -Verbose -Force -Recurse dist "${{env.DOTNET_ROOT}}/myapp/PortfolioClient"
          echo "Dist folder copied!"
          Copy-Item -Verbose -Force -Recurse src/assets "${{env.DOTNET_ROOT}}/myapp/PortfolioClient/dist"
          echo "Assets folder copied!"
          ls "${{env.DOTNET_ROOT}}/myapp/PortfolioClient/dist"

      # - name: Publish vue.js
      #   run: |
      #     cd PortfolioClient
      #     ls dist
      #     cp dist "${{env.DOTNET_ROOT}}/myapp"
      #     echo "Dist folder copied!"
      #     cp -verbose src/assets "${{env.DOTNET_ROOT}}/myapp/dist"
      #     echo "Assets folder copied!"
      #     ls "${{env.DOTNET_ROOT}}/myapp/dist"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
        
      # - name: Show deploy location
      #   run: |
      #     ls "${{env.DOTNET_ROOT}}/myapp"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mstabryla-portfolio'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C0F0B006857E43B59A0DDD212035B8F1 }}